/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-10-28 03:42:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ohora;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oho_005fmemInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730083643443L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/Ohora-JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jspPro/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/cdn-main/oho_memInfo.css\">\r\n");
      out.write("<script src=\"../resources/js/oho_memInfo.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <div id=\"contents\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"subSection\">\r\n");
      out.write("                <h2 class=\"subTitle\">\r\n");
      out.write("                    <span>member modify</span>\r\n");
      out.write("                </h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"member-edit-cont\">\r\n");
      out.write("                <div class=\"mem-edit-layout\">\r\n");
      out.write("                    <form action=\"\" method=\"post\" id=\"editForm\" name=\"editForm\" >\r\n");
      out.write("                        <!-- form 상단에 엄청난 인풋들이 히든으로 숨겨져 있으나 용도를 알 수 없음(아마 암호화 관련?). 생략 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"member-edit-wrap\">\r\n");
      out.write("                         <!-- 멤버 에딧 랩 == xans-element- xans-member xans-member-edit -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"edit-table-wrap\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"edit-table-top-wrap\">\r\n");
      out.write("                                    <div class=\"table-title\">기본정보</div>\r\n");
      out.write("                                    <div class=\"pilsu-wrap\">\r\n");
      out.write("                                        <span class=\"th-required\" style=\"font-size: 16px;\">*</span>\r\n");
      out.write("                                        <span class=\"required\">필수입력사항</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"memeber-info-container\">\r\n");
      out.write("\r\n");
      out.write("                                    <table>\r\n");
      out.write("                                        <colgroup>\r\n");
      out.write("                                            <col style=\"width:200px;\">\r\n");
      out.write("                                            <col style=\"width:auto;\">\r\n");
      out.write("                                        </colgroup>\r\n");
      out.write("\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <!-- 행으로 보는 표라는 뜻 -->\r\n");
      out.write("                                                    <span class=\"th-title\">아이디</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <input type=\"text\" readonly=\"readonly\" id=\"member-id\" name=\"member-id\" >\r\n");
      out.write("                                                    <span class=\"SP_stxt\">(영문소문자/숫자, 4~16자)</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">비밀번호</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <input type=\"password\"  id=\"passwd\" name=\"passwd\" maxlength=\"16\">\r\n");
      out.write("                                                    <div class=\"pw-guideBox-wrap\">\r\n");
      out.write("                                                        <div class=\"pw-guideBox\">\r\n");
      out.write("                                                            <div class=\"pw-guide-content\">\r\n");
      out.write("                                                                <div class=\"pw-guide-tit\">※ 비밀번호 입력 조건</div>\r\n");
      out.write("                                                                <div class=\"pw-guide-list\">\r\n");
      out.write("                                                                    - 대소문자/숫자/특수문자 중 2가지 이상 조합, 8자~16자<br>\r\n");
      out.write("                                                                    - 입력 가능 특수문자 <br>&nbsp;&nbsp;&nbsp;  ~ ` ! @ # $ % ^ ( ) * _ - = { } [ ] | ; : &lt; &gt; , . ? /<br>\r\n");
      out.write("                                                                    - 공백 입력 불가능<br>\r\n");
      out.write("                                                                    - 연속된 문자, 숫자 사용 불가능<br>\r\n");
      out.write("                                                                    - 동일한 문자, 숫자를 반복해서 사용 불가능<br>\r\n");
      out.write("                                                                    - 아이디 포함 불가능               \r\n");
      out.write("                                                                    <!-- 입력 창에 포커스가면 튀어나옴 -->\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"pw-guide2\">\r\n");
      out.write("                                                        (영문 대소문자/숫자/특수문자 중 2가지 이상 조합, 8자~16자)\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                               <th scope=\"row\">\r\n");
      out.write("                                                <span class=\"th-title\">비밀번호 확인</span>\r\n");
      out.write("                                                <span class=\"th-required\">*</span>\r\n");
      out.write("                                               </th> \r\n");
      out.write("                                               <td>\r\n");
      out.write("                                                    <input type=\"password\" id=\"passwd-confirm\" name=\"passwd-confirm\" maxlength=\"16\">\r\n");
      out.write("                                                    <span id=\"pwConfirmMsg\" class=\"\"></span>\r\n");
      out.write("                                                    <!-- 이 span은 비밀번호 확인 다르게 입력하면 class에 error 추가되면서 글 튀어나옴 -->\r\n");
      out.write("                                               </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">이름</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <input type=\"text\" id=\"name\" name=\"name\" maxlength=\"30\" readonly=\"readonly\" value=\"박준용\">\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">주소</span>\r\n");
      out.write("                                                    <span class=\"th-required displayNone\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div class=\"address\">\r\n");
      out.write("                                                        <input type=\"text\" readonly=\"readonly\" maxlength=\"14\" id=\"postcode1\" name=\"postcode1\" >\r\n");
      out.write("                                                        <a href=\"#\" class=\"postBtn\" onclick=\"addrFinder()\" id=\"postBtn\">우편번호</a>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"address\">\r\n");
      out.write("                                                        <input type=\"text\" readonly=\"readonly\" id=\"addr1\" name=\"addr1\">\r\n");
      out.write("                                                        <span class=\"addrguide\">기본주소</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"address\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"addr2\" name=\"addr2\">\r\n");
      out.write("                                                        <span class=\"addrguide\">나머지주소</span>\r\n");
      out.write("                                                        <span class=\"addrguide\">(선택입력가능)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">일반전화</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <select id=\"phone1\" name=\"phone[]\">\r\n");
      out.write("                                                        <option value=\"02\">02</option>\r\n");
      out.write("                                                        <option value=\"031\">031</option>\r\n");
      out.write("                                                        <option value=\"032\">032</option>\r\n");
      out.write("                                                        <option value=\"033\">033</option>\r\n");
      out.write("                                                        <option value=\"041\">041</option>\r\n");
      out.write("                                                        <option value=\"042\">042</option>\r\n");
      out.write("                                                        <option value=\"043\">043</option>\r\n");
      out.write("                                                        <option value=\"044\">044</option>\r\n");
      out.write("                                                        <option value=\"051\">051</option>\r\n");
      out.write("                                                        <option value=\"052\">052</option>\r\n");
      out.write("                                                        <option value=\"053\">053</option>\r\n");
      out.write("                                                        <option value=\"054\">054</option>\r\n");
      out.write("                                                        <option value=\"055\">055</option>\r\n");
      out.write("                                                        <option value=\"061\">061</option>\r\n");
      out.write("                                                        <option value=\"062\">062</option>\r\n");
      out.write("                                                        <option value=\"063\">063</option>\r\n");
      out.write("                                                        <option value=\"064\">064</option>\r\n");
      out.write("                                                        <option value=\"0502\">0502</option>\r\n");
      out.write("                                                        <option value=\"0503\">0503</option>\r\n");
      out.write("                                                        <option value=\"0504\">0504</option>\r\n");
      out.write("                                                        <option value=\"0505\">0505</option>\r\n");
      out.write("                                                        <option value=\"0506\">0506</option>\r\n");
      out.write("                                                        <option value=\"0507\">0507</option>\r\n");
      out.write("                                                        <option value=\"070\">070</option>\r\n");
      out.write("                                                        <option value=\"010\">010</option>\r\n");
      out.write("                                                        <option value=\"011\">011</option>\r\n");
      out.write("                                                        <option value=\"016\">016</option>\r\n");
      out.write("                                                        <option value=\"017\">017</option>\r\n");
      out.write("                                                        <option value=\"018\">018</option>\r\n");
      out.write("                                                        <option value=\"019\">019</option>\r\n");
      out.write("                                                        <option value=\"0508\">0508</option>\r\n");
      out.write("                                                    </select>-<input id=\"phone2\" name=\"phone[]\" maxlength=\"4\"  value=\"\" type=\"text\">-<input id=\"phone3\" name=\"phone[]\" maxlength=\"4\" value=\"\" type=\"text\">\r\n");
      out.write("                                                </td>\r\n");
      out.write("\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">휴대전화</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div id=\"mobile-input\">\r\n");
      out.write("                                                        <select id=\"mobile1\" name=\"mobile[]\">\r\n");
      out.write("                                                            <option value=\"010\">010</option>\r\n");
      out.write("                                                            <option value=\"011\">011</option>\r\n");
      out.write("                                                            <option value=\"016\">016</option>\r\n");
      out.write("                                                            <option value=\"017\">017</option>\r\n");
      out.write("                                                            <option value=\"018\">018</option>\r\n");
      out.write("                                                            <option value=\"019\">019</option>\r\n");
      out.write("                                                        </select>\r\n");
      out.write("                                                         - \r\n");
      out.write("                                                        <input id=\"mobile2\" name=\"mobile[]\" maxlength=\"4\"  value=\"\" type=\"text\">\r\n");
      out.write("                                                         - \r\n");
      out.write("                                                        <input id=\"mobile3\" name=\"mobile[]\" maxlength=\"4\" value=\"\" type=\"text\">\r\n");
      out.write("                                                        <button type=\"button\" id=\"btn-verify-mobile\" onclick=\"alert('간편인증 온클릭')\">간편인증</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"must-write\">\r\n");
      out.write("                                                        <!-- 간편인증 누르면 튀어나와서 인증번호 쓰라는 칸인데 일단 패스 -->\r\n");
      out.write("                                                         <!-- 만약 구현할거면 class=must-write 찾아서 구현.. -->\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">SMS 수신여부</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td class=\"SP_RadioBox\">\r\n");
      out.write("                                                    <input id=\"is_sms0\" name=\"is_sms\" value=\"T\" type=\"radio\">\r\n");
      out.write("                                                    <label for=\"is_sms0\">수신함</label>\r\n");
      out.write("                                                    <input id=\"is_sms1\" name=\"is_sms\" value=\"F\" type=\"radio\" checked=\"checked\">\r\n");
      out.write("                                                    <label for=\"is_sms1\">수신안함</label>\r\n");
      out.write("                                                    <p class=\"SP_stxt SP_pdTop5\">쇼핑몰에서 제공하는 유익한 이벤트 소식을 SMS로 받으실 수 있습니다.</p>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">이메일</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <input type=\"text\" id=\"email1\" name=\"email1\">\r\n");
      out.write("                                                    <span id=\"emailMsg\" class=\"\"></span>\r\n");
      out.write("                                                    <!-- 얘도 형식 어긋나면 error 클래스 추가되면서 옆에 튀어나옴 -->\r\n");
      out.write("                                                    <!-- 공백 시에는 이메일을 입력해 주세요. 라고 나옴 -->\r\n");
      out.write("                                                    <!-- 중복 시에는  이미 사용중인 이메일입니다. 다른 이메일로 다시 시도해 주세요. 라고 나옴 -->\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">이메일 수신여부</span>\r\n");
      out.write("                                                    <span class=\"th-required\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("\r\n");
      out.write("                                                <td class=\"SP_RadioBox\">\r\n");
      out.write("                                                    <input id=\"is_news_mail0\" name=\"is_news_mail\" value=\"T\" type=\"radio\">\r\n");
      out.write("                                                    <label for=\"is_news_mail0\">수신함</label>\r\n");
      out.write("                                                    <input id=\"is_news_mail1\" name=\"is_news_mail\" value=\"F\" type=\"radio\" checked=\"checked\">\r\n");
      out.write("                                                    <label for=\"is_news_mail1\">수신안함</label>\r\n");
      out.write("                                                    <p class=\"SP_stxt SP_pdTop5\">쇼핑몰에서 제공하는 유익한 이벤트 소식을 이메일로 받으실 수 있습니다.</p>\r\n");
      out.write("                                                </td>\r\n");
      out.write("\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"edit-table-wrap\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"edit-table-top-wrap\">\r\n");
      out.write("                                    <div class=\"table-title\">추가정보</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"additional-info-wrap\">\r\n");
      out.write("                                    <table class=\"additional-table\">\r\n");
      out.write("                                        <colgroup>\r\n");
      out.write("                                            <col style=\"width:150px;\">\r\n");
      out.write("                                            <col style=\"width:auto;\">\r\n");
      out.write("                                        </colgroup>\r\n");
      out.write("\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">\r\n");
      out.write("                                                    <span class=\"th-title\">생년월일</span>\r\n");
      out.write("                                                    <span class=\"th-required displayNone\">*</span>\r\n");
      out.write("                                                </th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <input id=\"birth_year\" name=\"birth_year\" class=\"inputTypeText\" maxlength=\"4\" value=\"\" type=\"text\">\r\n");
      out.write("                                                    년\r\n");
      out.write("                                                    <input id=\"birth_month\" name=\"birth_month\" class=\"inputTypeText\" maxlength=\"2\" value=\"\" type=\"text\">\r\n");
      out.write("                                                    월\r\n");
      out.write("                                                    <input id=\"birth_day\" name=\"birth_day\" class=\"inputTypeText\" maxlength=\"2\" value=\"\" type=\"text\">\r\n");
      out.write("                                                    일\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 추가 정보 테이블 (생일) -->\r\n");
      out.write("\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <h3>개인정보 처리 위탁 동의(선택)</h3>\r\n");
      out.write("                                <div class=\"info-use-agree-wrap\">\r\n");
      out.write("                                    <div class=\"info-use-content\">\r\n");
      out.write("                                        <div class=\"view-privacy-optional\">아래 내용의 동의 여부는 회원가입에 영향을 미치지 않습니다. 단, 동의 거부시 서비스 이용에 제한이 있을 수 있습니다.<br>\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            - 위탁받는 자(수탁업체) : (주)데이터라이즈<br>\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            - 위탁업무의 내용:<br>\r\n");
      out.write("                                            목적 - 사용자 행태 기반의 맞춤형 정보 제공. SMS, 카카오톡 채널 및 E-mail 등의 메시지 발송에 필요한 정보. 이벤트 전달 및 분석리포트 업무.<br>\r\n");
      out.write("                                            항목 - [일반] 이름, 아이디, 휴대폰번호, 이메일 주소<br>\r\n");
      out.write("                                            보유기간 - 계약종료시까지<br>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"check\">\r\n");
      out.write("                                        <span>개인정보 처리 위탁에 동의하십니까?</span>\r\n");
      out.write("                                        <input type=\"checkbox\" id=\"infoUse-agree\" name=\"infoUse-agree\">\r\n");
      out.write("                                        <label for=\"infoUse-agree\"></label>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"SP_submitBtn_wrap\">\r\n");
      out.write("                                <div class=\"SP_submitBtn_left\">\r\n");
      out.write("                                    <a href=\"\" class=\"cnclBtn\">취소</a>\r\n");
      out.write("                                    <a href=\"\" class=\"memDelBtn\" onclick=\"\">회원탈퇴</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"SP_submitBtn_right\">\r\n");
      out.write("                                    <a href=\"\" class=\"modifyBtn\" onclick=\"\">회원정보수정</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 멤버 에딧 랩 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        </div>    \r\n");
      out.write("        <!-- 전체 contents 끝 -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 전체 container 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function addrFinder() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('postcode1').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"addr1\").value = addr;\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"addr1\").value += extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"addr1\").value += '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"addr2\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"oho_memInfo.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
